export default {
    HeroHeading: 'AI Logo Maker',
    HeroSubHeading: 'Create your own logo in minutes',
    HeroDesc: 'Get Started',
    InputTitlePlaceholder: 'Enter your logo name',
    LogoTitle: 'Logo Title',
    LogoTitleDesc: 'Provide a title for your logo that best represents your brand or idea.',
    LogoDescTitle: 'Logo Description',
    LogoDescDesc: 'Describe the concept or theme of your logo to guide the design process.',
    LogoIdeaTitle: 'Logo Ideas',
    LogoIdeaDesc: 'Browse through unique logo ideas tailored to your preferences.',
    LogoDesignTitle: 'Design Your Logo',
    LogoDesignDesc: 'Customize your logo’s font, style, and layout for a unique identity.',
    LogoColorPaletteTitle: 'Choose a Color Palette',
    LogoColorPaletteDesc: 'Select a color palette that matches your brand’s theme and values.',
};
